[package]
name = "menoetius_macro"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]

[dependencies]
rapace = { git = "https://github.com/bearcove/rapace.git", features = ["stream"] }
tokio = { version = "1", features = ["process"] }
tempfile = "3"
menoetius = { path = "../menoetius" }
miette = "7.6.0"
thiserror = "2.0.17"
