[package]
name = "app"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
menoetius_macro = { path = "../menoetius_macro" }
my_plugin_hello_macro = { path = "../my_plugin_hello_macro" }

[build-dependencies]
menoetius = { path = "../menoetius" }
my_plugin_hello = { path = "../my_plugin_hello" }
menoetius_build = { path = "../menoetius_build" }
tokio = { version = "1", features = ["rt-multi-thread"] }
