[package]
name = "menoetius_build"
version = "0.1.0"
edition = "2024"

[dependencies]
menoetius = { path = "../menoetius" }
rapace = { git = "https://github.com/bearcove/rapace.git", features = ["stream"] }
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
